spring.application.name=Reelify

# Cassandra
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=reelify
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create-if-not-exists

minio.endpoint=http://192.168.1.9:19000
minio.access-key=plane_minio_access
minio.secret-key=plane_minio_s3cr3t_key
minio.bucket=reelify